image: deeson/default-pipeline:latest

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - make test

  branches:
    master:
      - step:
          script:
            - make test
            - make deploy-stage
    develop:
      - step:
          script:
            - make test
            - make deploy-test
  tags:
    '*':
      - step:
          script:
            - make test
            - make deploy-prod
